### ISSUE TITLE
Not receiving emails anymore

### ISSUE THREAD

**Issue by kuehlschrank** [JasonBarnabe/greasyfork#372]
I have stopped receiving script discussion notifications somewhere after May 20.
Password reset emails don't reach me either.
I don't use a spam filter (neither client-side nor server-side).
User ID / name = 12 / kuehlschrank
Please don't publish my address here.

**Comment by JasonBarnabe** [comment]
I can get password reset emails, but for some reason now they come from noone@example.com.

**Comment by tobbexiv** [comment]
I did not try passwort reset, because i use a third party login, but to me it seems that some providers block addresses from ...@example.com as it is clearly that there can be no mail sent from this domain.

I just noticed a comment to one of my scripts after seeing this thread and was not able to find any notification email about this comment.

So it would be very nice if you can change the sender back to noreply@greasyfork.com

**Comment by JasonBarnabe** [comment]
Password resets have been coming from noone@example.com at least since https://github.com/JasonBarnabe/greasyfork/commit/e8a74ffca98a5dbcdc9ef3c2360044c10ed25885#diff-a8a4112d0760c0fd11f691c6a5fb22ad. Fixed now.

I just tested discussion notifications, and no problem there.

**Comment by kuehlschrank** [comment]
That didn't fix my problem. I'm still not receiving mails on my gmx.com account. I now use a different address for greasyfork (different hoster) which works fine.
This can be left closed but you probably want to check your mail logs, blacklists, etc.
