### ISSUE TITLE
Didn't get an email notification for a reply to a specific script discussion I've started

### ISSUE THREAD

**Issue by darkred** [JasonBarnabe/greasyfork#626]
I didn't get email notification for a reply to a specific script discussion I've started. 
Here is the script discussion URL :
https://greasyfork.org/en/forum/discussion/60796/minimum-imdb-rating-filter-should-not-be-applied-in-browser-mode-search-by-imdb-id

<details>
<summary>Screenshot of my 'Notification Preferences':</summary>

![2019-08-15_194349](https://user-images.githubusercontent.com/723651/63111011-60686f00-bf95-11e9-9555-cd7a554a5eca.jpg)
</details>

The reply was posted on July 24.
Since then, [one new discussion](https://greasyfork.org/en/forum/discussion/61671/) has been opened for one of my own scripts,
for which I've received an email notification, alright,
therefore the issue I describe seems to be not repeated.

**Comment by JasonBarnabe** [comment]
In the logs going back to July 15, the only attempt to send to your current email happened on August 13.

Unless you changed your email or notifications recently, seems like a bug.

**Comment by darkred** [comment]
> Unless you changed your email or notifications recently.

Thanks for the quick response. No, I haven't changed my email or notifications.

**Comment by JasonBarnabe** [comment]
Due to an nginx misconfiguration, JSON requests weren't working. This affected notifications, view counts, and probably more. Fixed now.

**Comment by vanowm** [comment]
The issue still present. As a script admin I only receive email notifications when a new discussion started, no email notification when replies posted.
