### ISSUE TITLE
Give authors advance notice of script deletion instead of just deleting the script

### ISSUE THREAD

**Issue by WoLpH** [JasonBarnabe/greasyfork#977]
I have half a dozen scripts in my tampermonkey that have suddenly been deleted so I've just resolved to disabling auto-update for the time being.

While I agree with the rationale of disallowing certain scripts, there are a few things wrong with the current handling:
1. The message is wrong: `This script was deleted from Greasy Fork, and due to its negative effects, it has been automatically removed from your browser.`
  What negative effects? This seriously hurts the reputation for a script and can probably make users uninstall a script.
2. There has been no warning or heads-up for developers telling them that the scripts are not up to the standards of the newly implemented scripts.

I would personally propose the following solution in this order:
1. rollback of the script deletions
2. send notice to all developers why their scripts will be deleted
3. delete after a grace period of a month or so

**Comment by JasonBarnabe** [comment]
> The message is wrong: This script was deleted from Greasy Fork, and due to its negative effects, it has been automatically removed from your browser.
> What negative effects? This seriously hurts the reputation for a script and can probably make users uninstall a script.

"Negative effects" are spam, malware, abusive, and illegal scripts; however, for a few weeks ending recently, all deletions were causing this message. This has been fixed.

> There has been no warning or heads-up for developers telling them that the scripts are not up to the standards of the newly implemented scripts.

Except possibly in cases like malware or spam, script authors will receive an email notification and will have 3 days to respond (e.g. by fixing the issue or refuting the claim). In addition, after deletion, script authors can appeal the decision (again, by fixing the issue or refuting the claim).

**Comment by WoLpH** [comment]
> > The message is wrong: This script was deleted from Greasy Fork, and due to its negative effects, it has been automatically removed from your browser.
> > What negative effects? This seriously hurts the reputation for a script and can probably make users uninstall a script.
> 
> "Negative effects" are spam, malware, abusive, and illegal scripts; however, for a few weeks ending recently, all deletions were causing this message. This has been fixed.

Excellent!

I do wonder though, is that a fix only for scripts that will be deleted in the future or for the ones already deleted? I'm still seeing that message for multiple scripts currently.

> > There has been no warning or heads-up for developers telling them that the scripts are not up to the standards of the newly implemented scripts.
> 
> Except possibly in cases like malware or spam, script authors will receive an email notification and will have 3 days to respond (e.g. by fixing the issue or refuting the claim). In addition, after deletion, script authors can appeal the decision (again, by fixing the issue or refuting the claim).

That's quite odd. Only one of the scripts I've written has been affected (8 days ago due to minified code) and I haven't seen any email about it. I only noticed when greasemonkey told me the script had been updated and deleted.

I have received mails from greasyfork in the past and I don't see any mails in the spam either. Do you have any idea what has happened in that case?

Slightly off-topic, isn't 3 days a bit short? It can take a little work to update at times and I personally don't always have time at a moments' notice.

**Comment by JasonBarnabe** [comment]
> I do wonder though, is that a fix only for scripts that will be deleted in the future or for the ones already deleted? I'm still seeing that message for multiple scripts currently.

This is only going forward. Previously it was a judgment call on the moderator's part.

> I have received mails from greasyfork in the past and I don't see any mails in the spam either. Do you have any idea what has happened in that case?

If you tell me what script you're talking about, I can check the logs to see if an email was attempted.

> Slightly off-topic, isn't 3 days a bit short? It can take a little work to update at times and I personally don't always have time at a moments' notice.

First off, the rules existed before the script was posted, and the new script page explicitly mentions the most common issues.

We need to strike a balance between giving authors time to update and protecting the users (or other authors). In most cases, there is either no fix (e.g. you copied code without permission) or an easy fix (e.g. don't run your code through a minifier).

**Comment by WoLpH** [comment]
For me personally it was this script which has existed for a very long time: https://greasyfork.org/en/scripts/1120-universal-syntax-highlighter
As far as I know, there was no easy way to integrate externals back when I wrote it, but I could be wrong. 

Seeing the storm of deleted scripts over the last week I assumed it was a new thing, I've never seen it before.

**Comment by JasonBarnabe** [comment]
> For me personally it was this script which has existed for a very long time: https://greasyfork.org/en/scripts/1120-universal-syntax-highlighter

I see an email sent out to you on Aug 13 (when the report was created) and Aug 16 (when it was resolved by a moderator). Not sure why you wouldn't have seen it.

**Comment by WoLpH** [comment]
Very strange... but in that case I think this issue is invalid. Thank you so much for the quick response!
